# Path to your oh-my-zsh configuration.
export ZSH=$HOME/playground/scripts/oh-my-zsh

# add a function path
#fpath=($ZSH/functions $fpath)

# Load all of the config files in ~/oh-my-zsh that end in .zsh
for config_file ($ZSH/*.zsh) source $config_file

# Customize to your needs...
#export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/core_perl
export EDITOR=vim

# my aliases
alias cyberoam='curl -s http://10.100.56.55:8090/httpclient.html -d "mode=191&username=200801001&password=200801001" | grep "<message>.*</message>" -o | sed "s/<\/*message>//g"'
alias bb="curl -s http://192.168.1.1/webconfig/wan/wan.html -u admin:4129 | grep \"connect\|disconnect\" -iwo | head -n1 | sed 's/Disconnect/✔ Up/g' | sed 's/Connect$/✘ Down/g'"
alias sl='dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Suspend'
alias slp='slock &; sl'
alias atm='cat ~/Softwares/card | xclip'
alias ksr='source /home/viranch/kde/bashrc; cs'
x=$(cat /proc/cpuinfo|grep processor|wc -l)
alias m='make -j$((x+1))'
alias mi='sudo make install -j$((x+1))'
compdef _which whose=which
compdef _pacman p=pacman
compdef _sudo _=sudo

# script aliases
alias imdb='python2 $HOME/playground/scripts/imdb.py'
alias aurman='sh $HOME/playground/scripts/aurman.sh'
alias trunkman='sh $HOME/playground/scripts/trunkman.sh'
alias tt='vim $HOME/time_table'
alias usage='sh $HOME/playground/scripts/broadband_usage.sh'
alias skins-dl='python2 $HOME/playground/stuff/skins.be/skins-dl.py'
alias chiface='sh $HOME/playground/scripts/change_iface.sh $HOME/Softwares/Arch/conky-arch2/'
alias text='python2 $HOME/playground/scripts/way2sms.py 9374394249'

# Git aliases
function current_branch() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo ${ref#refs/heads/}
}

alias g='git'
compdef _git g=git
alias gi='git init'
compdef _git gi=git-init
alias gcl='git clone'
compdef _git gcl=git-clone
alias gco='git checkout'
compdef _git gco=git-checkout
alias gst='git status'
compdef _git gst=git-status
alias gl='git pull'
compdef _git gll=git-pull
alias gd='git diff'
compdef _git gd=git-diff
alias gc='git commit -am'
compdef _git gc=git-commit
alias gp='git push'
compdef _git gp=git-push
alias glg='git log --max-count=5'
compdef _git glg=git-log

# Qt functions
function qtmake() {
    local srcFolder
    srcFolder=$(pwd)
    mkdir -p ../build
    cd ../build
    qmake $srcFolder
    make -j3
}

